### ISSUE TITLE
Migrate to dib-lab/kevlar

### ISSUE THREAD

**Issue by standage** [dib-lab/kevlar#10]
cc @ctb

- lab branding
- organizations >> individuals for sake of longevity

Will migrate once open PR(s) are merged.

**Comment by ctb** [comment]
err, dib-lab/kevlar, right?

main trick is not to fork it into dib-labg, but instead to import (so that the
parent repo is properly reported).  although we can ask github support to
migrate, also.

--t

**Comment by standage** [comment]
Yeah, I fixed the typo right after I hit enter :-)

I've used the automatic migrate feature several times recently, and I'm very satisfied. It's painless, and even redirects old location --> new location.

**Comment by ctb** [comment]
ok

On Tue, Dec 06, 2016 at 11:14:23AM -0800, Daniel Standage wrote:
> Yeah, I fixed the typo right after I hit enter :-)
> 
> I've used the automatic migrate feature several times recently, and I'm very satisfied. It's painless, and even redirects old location --> new location.
> 
> -- 
> You are receiving this because you were mentioned.
> Reply to this email directly or view it on GitHub:
> https://github.com/standage/kevlar/issues/10#issuecomment-265243683
-- 
C. Titus Brown, ctbrown@ucdavis.edu

**Comment by standage** [comment]
Done.
