### ISSUE TITLE
Parallelize based on sequence content

### ISSUE THREAD

**Issue by standage** [dib-lab/kevlar#15]
Our current workflow and scripts support the idea of splitting data by chromosome, which is intended to:

- make memory consumption more manageable
- support parallel processing
- make results smaller and easier to evaluate and interpret

The problem is that we want this to be a reference-free method, but we're relying increasingly on the reference and read mappings against the reference. The current criteria in `kevlar dump` are:

- If the read alignment is a secondary or supplementary alignment, discard
- If the read matches the reference genome perfectly, discard
- If the read aligns to the chromosome of interest, do not discard
- If at least half of the k-mers in the read are not present in the genome mask (the reference genome minus the chromosome of interest), do not discard

The first two points are fine, and when mapping data happens to be available we can leverage it. But we keep on running into problems with the second two points.

Today we discussed the following alternative approach.

- In an initial run, consider only k-mers beginning with the nucleotide 'A'. As before, find those that are abundant in the proband and "absent" (for some value of "absent") in the parents. Record these "interesting" k-mers.
- Repeat the run, but the second time consider only k-mers beginning with 'C'. The third time 'G', the fourth time 'T'.
- Once we have a combined list of interesting k-mers, we can go over all of the proband reads, keep only the reads containing interesting k-mers, and use this to group k-mers by event (using the corresponding linear paths or assemblies).

A couple of considerations.

- If reads are in BAM format, we could still take advantage of the reference genome to discard trivially uninteresting reads early on in the workflow.
- When collecting reads with interesting k-mers, we may want to do a second pass to collect reads that share k-mers with reads containing interesting k-mers.
- Rather than using a single nucleotide as a prefix, we could use a prefix of arbitrary length to split up the work as much as we'd like. One consideration is that some prefixes will be much more abundance than others.

**Comment by ctb** [comment]
A simple modification is to compute a murmur hash on the first k-mer in each reads, then divide up reads across hash space (e.g.` if hash(kmer) % NUM_WORKERS == this_worker: ...`.  This should be largely independent of sequence content.

**Comment by standage** [comment]
It's not just splitting up the counting that's important here, it's also having all of the relevant data accessible. When I'm checking to see if a k-mer is abundant in the proband and absent from the parent, I want to be sure that all of the relevant k-mers have been counted. Using a common prefix assures that, but hashing the first k-mer in the read does not.

**Comment by ctb** [comment]
Ahh, yes. Hashing each k-mer in the read would, however.

**Comment by ctb** [comment]
But wait... I'm not sure why you're thinking about doing this anyway. This seems like optimization. What bottleneck are you running into? Or am I missing something?

**Comment by standage** [comment]
Still motivated by the first 3 points. So yeah, optimization I guess.

**Comment by fhormozd** [comment]
If I understand correctly what titus is suggesting will work (and it is a generalization of what we discussed).

**Comment by standage** [comment]
I think so, and it avoids the issue that some prefixes (i.e. A-rich ones) will be more abundant than others.

**Comment by fhormozd** [comment]
Exactly.

**Comment by ctb** [comment]
It has been my mantra that multiple passes across the data are more likely
to be bad than anything else, but I could be wrong :).

**Comment by standage** [comment]
We're exploring memory vs runtime trade offs. A single pass right now for a human trio requires > 100 Gb.

**Comment by ctb** [comment]
ahh. how are you choosing the fp rate?

**Comment by standage** [comment]
Not very smartly: trial and error. Guess I should already have run the hyper log log already.

**Comment by ctb** [comment]
On Thu, Dec 22, 2016 at 07:31:32AM -0800, Daniel Standage wrote:
> Not very smartly: trial and error. Guess I should already have run the hyper log log already.

:)

my guess is you can get by with quite a high fp rate for the initial pass;
a fp rate of 10% means that the average count is off by 10%, and you should
not get a lot of really erroneous counts.

**Comment by standage** [comment]
Closed now that k-mer banding support has been merged in #23.
