### ISSUE TITLE
Unclear if python 2 or 3

### ISSUE THREAD

**Issue by tseemann** [dib-lab/kevlar#280]
All instructions say `pip` which is py2 under current PEP rules.

I assume you mean `pip3` ?

**Comment by standage** [comment]
Yes, you're correct. I didn't realize how unclear the install docs are on this until re-reading just now. Vestiges from when kevlar supported py2 and py3.

Is there any chance you could share a link the relevant PEP? My Google Fu is failing me.

**Comment by tseemann** [comment]
https://www.python.org/dev/peps/pep-0394/
