### ISSUE TITLE
Contig assembly

### ISSUE THREAD

**Issue by standage** [dib-lab/kevlar#48]
A while ago I replaced linear path assembly with junction count assembly in the `kevlar collect` step. This eliminated problems we previously had with cyclical structure in the assembly graph, but it doesn't seem to have done much about truncation at sequencing errors. I've been playing around with khmer's simple labeled assembler, but this will take some effort to get working.

@ctb suggested investigating abundance-based trimming / spur removal. Probably a medium-term priority.

In the mean time, I assembled the reads described in https://github.com/dib-lab/khmer/issues/1657 with velvet (using vanilla parameters) and got almost the entire consensus sequence of the reads' multiple sequence alignment. If we can get partitioning working well, one preliminary approach could be to simply delegate assembly of each distinct CC to a third-party assembler.

**Comment by ctb** [comment]
I've always admired Velvet for its simple "let's assemble that for you!" approach, with little in the way of fancy heuristics. :) The strategy of calling out to an assembler is one that @camillescott is also thinking of using for her streaming RNAseq foo.

There are a few countervailing reasons to pursue our own assembly approach. One is efficiency (forking is slow); another is installation headaches; and the third is flexibility/tuning that you're only going to get with a library approach.

(No objections to your proposed approach, just wanted to add some thoughts!)

**Comment by standage** [comment]
I definitely think having all the assembly functionality available from the library is the way to go in the long run. But I can duct tape kevlar and velvet together much more quickly than we can get the next khmer release out and begin expanding and refining and testing its assembly capabilities. :-)

**Comment by standage** [comment]
A greedy assembly algorithm (to find shortest common supersequence) was introduced with #66.

**Comment by standage** [comment]
Integrated `fermi-lite` for local assembly in #156, which appears to outperform both the greedy assembler and my naive khmer assembly apparatus by quite a bit.

**Comment by ctb** [comment]
good to know!
