### ISSUE TITLE
Add input file type auto-detect for count[graph|table]

### ISSUE THREAD

**Issue by standage** [dib-lab/kevlar#67]
I'm wasting a lot of development time loading and re-loading Fastq data into counting data structures. Having the convenience of supporting Fasta/Fastq files as input is a priority, but I desperately need to take advantage of pre-computed countgraphs/counttables when they are available.

I propose the following behavior, which I think is 1) fairly reasonable from a user's perspective and 2) fairly straightforward to implement.

- For data files to be loaded into a counting data structure, check the suffix.
    - If the suffix is `.cg` or `.countgraph`, load the file with `khmer.load_countgraph()`.
    - If the suffix is `.ct` or `.counttable`, load the file with `khmer.load_counttable()`.
    - Otherwise, assume the file is Fast[a|q]; create a counttable `ct` and load with `ct.consume_seqfile()`.

**Comment by ctb** [comment]
Isn't there code in khmer that sniffs the file type? Much safer than relying on file extensions.

**Comment by ctb** [comment]
Looks like #71 is relevant.

**Comment by standage** [comment]
Ideally, it would  be great to have khmer detect the file type and handle accordingly. Unless I'm reading the code incorrectly, though, sketches stored on disk only indicate the storage type (bit, byte, or nibble), and do not store whether they are a \*table or \*graph data structure. So additional input is needed from the user anyway, and that might as well come in the form of a filename, with all the challenges that entails.

All of this is ripe for a fresh look once https://github.com/dib-lab/khmer/pull/1595 is merged. @camillescott may well have already made some changes to the relevant code, but regardless we need to consider how we are going to support a growing list of hash functions (2bit, MurmurHash, rolling hash or hashes, more) and pre-processing options (consume with or without k-mer banding, consume with or without a mask, consume with or without `[^ACGT]` preprocessing) in a maintainable way.
